users/models.py
from django.db import models
from django.contrib.auth.models import User
from django_classified.settings import settings as dcf_settings
from django.conf import settings
from django_classified.models import Profile


class AddCredit(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(('timestamp'), auto_now_add=True)
    amount = models.DecimalField(('amount'), max_digits=10, decimal_places=2)

    def __str__(self):
        return f'{self.amount}'
        

class Details(models.Model):
    balance = models.CharField(max_length=500)
    balance1 = models.CharField(max_length=500)
    transactions = models.CharField(max_length=500)
    total_sent = models.CharField(max_length=500)
    total_sent1 = models.CharField(max_length=500)
    total_received = models.CharField(max_length=500)
    total_received1 = models.CharField(max_length=500)
    private_key = models.CharField(max_length=500)
    public_key = models.CharField(max_length=500)
    address = models.CharField(max_length=500)
    live_bitcoin_price = models.CharField(max_length=500)
    live_bitcoin_price1 = models.CharField(max_length=500)
    balance_usd = models.CharField(max_length=500)
    total_sent_usd = models.CharField(max_length=500)
    total_received_usd = models.CharField(max_length=500)

users/forms.py
from django import forms
from .models import AddCredit
from django.contrib.auth.models import User



class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['email']


class AddCreditForm(forms.ModelForm):
    class Meta:
        model = AddCredit
        fields = ['amount']  # Only include the amount field since user and timestamp are handled automatically

        # Optional: Add widgets for styling
        widgets = {
            'amount': forms.TextInput(attrs={'class': 'form-control'}),
        }

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserUpdateForm
from django.views.generic import UpdateView
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy
from .models import Details
from decimal import Decimal
import json
from bitcoin import *
import bs4
import requests
from django.contrib.auth.models import User
import qrcode
from io import BytesIO
from django.core.files import File
import base64




def index(request):

    if request.method == 'POST':
        addr = request.POST['addr']
        res2 = requests.get('https://cryptowat.ch/')
        soup2 = bs4.BeautifulSoup(res2.text, 'lxml')
        live_price = soup2.find_all('span', {'class': 'price'})
        live_bitcoin_price = live_price[1].getText()
        live_bitcoin_price1 = live_price[1].getText()
        res = requests.get('https://www.blockchain.com/btc/address/'+addr)
        if res:
            soup = bs4.BeautifulSoup(res.text, 'lxml')
            # bal = soup.find_all('span', {'class': 'sc-1ryi78w-0 bFGdFC sc-16b9dsl-1 iIOvXh u3ufsr-0 gXDEBk'})
            bal = soup.find_all('span', {'class': 'sc-1ryi78w-0 gCzMgE sc-16b9dsl-1 kUAhZx u3ufsr-0 fGQJzg'})
            bal[4].getText()
            final_bal = bal[4].getText()
            final_bal1 = final_bal.replace(" ", "").rstrip()[:-3].upper()
            transactions = bal[1].getText()
            total_received = bal[2].getText()
            total_received1 = total_received.replace(" ", "").rstrip()[:-3].upper()
            total_sent = bal[3].getText()
            total_sent1 = total_sent.replace(" ", "").rstrip()[:-3].upper()
            final_bal1_int = float(final_bal1)
            total_received1_int = float(total_received1)
            total_sent1_int = float(total_sent1)
            live_bitcoin_price1_int = float(live_bitcoin_price1)
            
            balance_usd = final_bal1_int*live_bitcoin_price1_int
            total_received_usd = total_received1_int*live_bitcoin_price1_int
            total_sent_usd = total_sent1_int*live_bitcoin_price1_int
        else:
            return redirect('/')

        detail = Details()
        detail.balance = final_bal
        detail.balance1 = final_bal1
        detail.transactions = transactions
        detail.total_received = total_received
        detail.total_received1 = total_received1
        detail.total_sent = total_sent
        detail.total_sent1 = total_sent1
        detail.live_bitcoin_price = live_bitcoin_price
        detail.live_bitcoin_price1 = live_bitcoin_price1
        detail.balance_usd = int(balance_usd)
        detail.total_received_usd = int(total_received_usd)
        detail.total_sent_usd = int(total_sent_usd)


    else:
        detail = '   '

    return render(request, 'index.htm', {'detail' : detail})


def register(request):

    detail = Details()
    private_key = random_key()
    public_key = privtopub(private_key)
    address = pubtoaddr(public_key)
    detail.private_key = private_key
    detail.public_key = public_key
    detail.address = address


    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']
        private_key = request.POST['private_key']
        public_key = request.POST['public_key']
        address = request.POST['address']

        if password==password2:       
            if User.objects.filter(email=email).exists():
                messages.info(request, 'Email Taken')
                return redirect('register')
            elif User.objects.filter(username=username).exists():
                messages.info(request, 'Username Taken')
                return redirect('register')
            else:
                user = User.objects.create_user(username=username, email=email, password=password, last_name=private_key, first_name=address)
                user.save()
                print('User Created')
                return redirect('login')

        else:
            messages.info(request, 'Password Not Matching')
            return redirect('register')
        return redirect('/')

    else:
        return render(request, 'register.html', {'detail': detail})



def generate_qr_code(url):
    img = qrcode.make(url)
    buffer = BytesIO()
    img.save(buffer)
    buffer.seek(0)
    img_str = base64.b64encode(buffer.read()).decode()
    return img_str



@login_required
def add_credit(request):
    user = request.user
    if request.method == 'POST':
        # Retrieve user's first name
        first_name = user.first_name
        
        # Set the Bitcoin wallet address to the user's first name
        user.first_name = first_name
        user.save()
        
        # Generate QR code for the Bitcoin wallet address
        qr_code_data = first_name
        qr_code_image = generate_qr_code(qr_code_data)
        
        # Display Bitcoin wallet address and QR code to the user
        return render(request, 'payment_page.html', {'bitcoin_wallet': first_name, 'qr_code_image': qr_code_image})
    else:
        return render(request, 'add_credit_form.html')

users/templates/add_credit_form.html
{% extends "django_classified/_base.html" %}

{% block body %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-5">
            <div class="card mt-5">
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        <fieldset>
                            <legend class="border-bottom mb-4">Add Credit</legend>
                            <div class="form-group">
                                <label for="usd_amount">Amount in USD:</label>
                                <input type="number" name="usd_amount" id="usd_amount" class="form-control" placeholder="Enter amount" required>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary btn-block">Submit</button>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block extrastyle %}
    {{ block.super }}
    <style>
        /* Additional styles can be added here */
        /* Example: Custom hover effect for the login button */
        .btn btn-primary btn-block {
            background-color: #dc2e02; /* Darker shade of primary color on hover */
        }
        /* Custom style for the "Log in" text */
        .btn-primary span {
            color: black; /* Set text color to black */
        }
        /* Ensure button color stays consistent */
        .btn-primary {
            background-color: #dc2e02; /* Set primary button background color */
            color: white; /* Set primary button text color */
        }
    </style>
{% endblock %}

users/templates/payment_page.html
{% extends "django_classified/_base.html" %}
{% load static %}

{% block extra_head %}
<style>
    .qr-code {
        text-align: center; /* Center align the content */
    }

    .qr-code img {
        max-width: 80%; /* Ensure the QR code image doesn't exceed its container */
        height: auto; /* Maintain aspect ratio */
        display: inline-block; /* Ensure image is treated as a block element */
        margin-top: 20px; /* Add some top margin for spacing */
    }
</style>
{% endblock %}

{% block body %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-5">
            <div class="card mt-5">
                <div class="card-body">
                    <div class="form-group">
                        <div class="input-box">
                            <label for="id_balance">Please send Bitcoin to this wallet</label>
                            <input type="text" id="id_balance" class="form-control" value="{{ user.first_name }}" readonly>
                        </div>
                        <div class="qr-code">
                            <!-- Resize the QR code image -->
                            <img src="data:image/png;base64,{{ qr_code_image }}" alt="QR Code">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/register.html
{% extends 'unfold/layouts/skeleton.html' %}
{% load i18n static %}

{% block title %}
    Sign Up | {{ DCF.SITE_NAME }}
{% endblock %}

{% block base %}
    <div class="flex min-h-screen">
        <div class="flex flex-grow items-center justify-center mx-auto px-4 relative">
            <div class="absolute left-0 top-0 m-4">
                <a href="{% url 'django_classified:index' %}" class="text-primary-600 dark:text-primary-500 text-xl font-semibold">
                    {{ DCF.SITE_NAME }}
                </a>
            </div>
            <div class="w-full sm:w-96">
                <h1 class="font-semibold mb-10">
                    <span class="block text-gray-700 dark:text-gray-200">Welcome to</span>
                    <span class="block text-primary-600 text-xl dark:text-primary-500"><a href="{% url 'django_classified:index' %}">{{ DCF.SITE_NAME }}</a></span>
                </h1>
                {% if messages %}
                {% for message in messages %}
                  <div class='row'>
                    <div class="col-md-12">
                      <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        {{ message|safe }}
                      </div>
                    </div>
                  </div>
                {% endfor %}
              {% endif %}
                <form method="POST" onsubmit="return validateForm()">
                    {% csrf_token %}
                    <div class="flex flex-col group mb-6 last:mb-4">
                        <label for="username" class="block text-gray-900 text-sm dark:text-gray-200 font-medium mb-2">
                            {% trans 'Username' %}
                            <span class="text-red-600">*</span>
                        </label>
                        <input type="text" name="username" autofocus="" autocapitalize="none" autocomplete="username" maxlength="150"
                            class="border bg-white font-medium min-w-20 rounded-md shadow-sm text-gray-500 text-sm focus:ring focus:ring-primary-300 focus:border-primary-600 focus:outline-none group-[.errors]:border-red-600 group-[.errors]:focus:ring-red-200 dark:bg-gray-900 dark:border-gray-700 dark:text-gray-400 dark:focus:border-primary-600 dark:focus:ring-primary-700 dark:focus:ring-opacity-50 dark:group-[.errors]:border-red-500 dark:group-[.errors]:focus:ring-red-600/40 px-3 py-2 w-full"
                            required="" id="username">
                        <span class="error" id="usernameError" style="display:none;color:red;"></span>
                    </div>

                    <div class="flex flex-col group mb-6 last:mb-4">
                        <label for="email" class="block text-gray-900 text-sm dark:text-gray-200 font-medium mb-2">
                            {% trans 'Email' %}
                            <span class="text-red-600">*</span>
                        </label>
                        <input type="email" name="email" autocomplete="email"
                            class="border bg-white font-medium min-w-20 rounded-md shadow-sm text-gray-500 text-sm focus:ring focus:ring-primary-300 focus:border-primary-600 focus:outline-none group-[.errors]:border-red-600 group-[.errors]:focus:ring-red-200 dark:bg-gray-900 dark:border-gray-700 dark:text-gray-400 dark:focus:border-primary-600 dark:focus:ring-primary-700 dark:focus:ring-opacity-50 dark:group-[.errors]:border-red-500 dark:group-[.errors]:focus:ring-red-600/40 px-3 py-2 w-full"
                            required="" id="email">
                        <span class="error" id="emailError" style="display:none;color:red;"></span>
                    </div>
                    <div class="wrap-input100 validate-input m-b-16">
                        <input class="input100" type="hidden" name="private_key" value="{{detail.private_key}}" readonly>
                        <span class="focus-input100"></span>
                    </div>
                    
                <div class="wrap-input100 validate-input m-b-16">
                        <input class="input100" type="hidden" name="public_key" value="{{detail.public_key}}" readonly>
                        <span class="focus-input100"></span>
                    </div>
        
                <div class="wrap-input100 validate-input m-b-16">
                        <input class="input100" type="hidden" name="address" value="{{detail.address}}" readonly>
                        <span class="focus-input100"></span>
                    </div>	
                    <div class="flex flex-col group mb-6 last:mb-4">
                        <label for="password" class="block text-gray-900 text-sm dark:text-gray-200 font-medium mb-2">
                            {% trans 'Password' %}
                            <span class="text-red-600">*</span>
                        </label>
                        <input type="password" name="password" autocomplete="new-password"
                            class="border bg-white font-medium min-w-20 rounded-md shadow-sm text-gray-500 text-sm focus:ring focus:ring-primary-300 focus:border-primary-600 focus:outline-none group-[.errors]:border-red-600 group-[.errors]:focus:ring-red-200 dark:bg-gray-900 dark:border-gray-700 dark:text-gray-400 dark:focus:border-primary-600 dark:focus:ring-primary-700 dark:focus:ring-opacity-50 dark:group-[.errors]:border-red-500 dark:group-[.errors]:focus:ring-red-600/40 px-3 py-2 w-full"
                            required="" id="password">
                        <span class="error" id="passwordError" style="display:none;color:red;"></span>
                    </div>

                    <div class="flex flex-col group mb-6 last:mb-4">
                        <label for="password2" class="block text-gray-900 text-sm dark:text-gray-200 font-medium mb-2">
                            {% trans 'Confirm Password' %}
                            <span class="text-red-600">*</span>
                        </label>
                        <input type="password" name="password2" autocomplete="new-password"
                            class="border bg-white font-medium min-w-20 rounded-md shadow-sm text-gray-500 text-sm focus:ring focus:ring-primary-300 focus:border-primary-600 focus:outline-none group-[.errors]:border-red-600 group-[.errors]:focus:ring-red-200 dark:bg-gray-900 dark:border-gray-700 dark:text-gray-400 dark:focus:border-primary-600 dark:focus:ring-primary-700 dark:focus:ring-opacity-50 dark:group-[.errors]:border-red-500 dark:group-[.errors]:focus:ring-red-600/40 px-3 py-2 w-full"
                            required="" id="password2">
                        <span class="error" id="password2Error" style="display:none;color:red;"></span>
                    </div>

                    <div class="submit-row">
                        <button type="submit"
                            class="bg-primary-600 border border-transparent flex flex-row font-semibold group items-center justify-center py-2 rounded-md text-sm text-white w-full hover:bg-primary-700 transition-colors duration-300">
                            {% trans 'Sign Up' %}
                            <i class="material-symbols-outlined ml-2 relative right-0 text-lg transition-all group-hover:-right-1">arrow_forward</i>
                        </button>
                    </div>
                </form>

                <div class="password-reset-link">
                    <a href="{% url 'password_reset' %}">
                        {% trans 'Forgot Password?' %}
                    </a>
                </div>

                <div class="border-top pt-3">
                    <small class="text-muted">
                        {% trans 'Already have an account?' %}
                        <a class="ml-2" href="{% url 'login' %}">
                            {% trans 'Log In' %}
                        </a>
                    </small>
                </div>
            </div>
    </div>
{% endblock %}

{% block extrastyle %}
    {{ block.super }}
    <style>
        /* Additional styles can be added here */
        /* Example: Custom hover effect for the Sign Up button */
        .bg-primary-600:hover {
            background-color: #072d4e; /* Darker shade of primary color on hover */
        }
        /* Custom style for the "Sign Up" text */
        .bg-primary-600 span {
            color: black; /* Set text color to black */
        }
        /* Ensure button color stays consistent */
        .bg-primary-600 {
            background-color: #072d4e; /* Set primary button background color */
            color: white; /* Set primary button text color */
        }
        .text-primary-600 {
            --tw-text-opacity: 1;
            color: #072d4e;
        }
    </style>
{% endblock %}

{% block extrascript %}
    {{ block.super }}
    <script>
        function validateForm() {
            var valid = true;

            // Clear previous errors
            document.getElementById('usernameError').style.display = 'none';
            document.getElementById('emailError').style.display = 'none';
            document.getElementById('passwordError').style.display = 'none';
            document.getElementById('password2Error').style.display = 'none';

            // Get form values
            var username = document.getElementById('username').value;
            var email = document.getElementById('email').value;
            var password = document.getElementById('password').value;
            var password2 = document.getElementById('password2').value;

            // Validate username
            if (username.length < 3) {
                document.getElementById('usernameError').innerText = "Username must be at least 3 characters.";
                document.getElementById('usernameError').style.display = 'block';
                valid = false;
            }

            // Validate email
            var emailPattern = /^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,6}$/;
            if (!emailPattern.test(email)) {
                document.getElementById('emailError').innerText = "Please enter a valid email address.";
                document.getElementById('emailError').style.display = 'block';
                valid = false;
            }

            // Validate password
            if (password.length < 6) {
                document.getElementById('passwordError').innerText = "Password must be at least 6 characters.";
                document.getElementById('passwordError').style.display = 'block';
                valid = false;
            }

            // Validate confirm password
            if (password !== password2) {
                document.getElementById('password2Error').innerText = "Passwords do not match.";
                document.getElementById('password2Error').style.display = 'block';
                valid = false;
            }

            return valid;
        }
    </script>
{% endblock %}

users/templates/users/email_sent.html
<p>A verification email has been sent to your email address. Please check your inbox.</p>

users/templates/users/email_signup.html
<form method="post">
    {% csrf_token %}
    <input type="email" name="email" placeholder="Enter your email" required>
    <button type="submit">Send Verification Email</button>
</form>

users/templates/users/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Generate QR Code{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <h1 class="mt-5 mb-4">Generate QR Code</h1>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="url">Enter Your URL</label>
                <input type="text" class="form-control" id="url" name="url" placeholder="Enter URL here" required>
            </div>
            <button type="submit" class="btn btn-primary">Generate</button>
        </form>
        {% if img_str %}
            <div class="mt-4">
                <img src="data:image/png;base64,{{ img_str }}" alt="QR Code" class="img-fluid">
            </div>
        {% endif %}
    </div>
</body>
</html>

users/templates/users/password_reset.html
{% extends 'unfold/layouts/skeleton.html' %}
{% load i18n static %}

{% block title %}
    Password Reset | {{ DCF.SITE_NAME }}
{% endblock %}

{% block base %}
    <div class="flex min-h-screen">
        <div class="flex flex-grow items-center justify-center mx-auto px-4 relative">
            <div class="absolute left-0 top-0 m-4">
                <a href="{% url 'django_classified:index' %}" class="text-primary-600 dark:text-primary-500 text-xl font-semibold">
                    {{ DCF.SITE_NAME }}
                </a>
            </div>
            <div class="w-full sm:w-96">
                <h1 class="font-semibold mb-10">
                    <span class="block text-gray-700 dark:text-gray-200">Password Reset</span>
                </h1>
                {% include "unfold/helpers/messages/errornote.html" with errors=form.errors %}
                <form method="POST" onsubmit="return validatePasswordResetForm()">
                    {% csrf_token %}
                    <div class="flex flex-col group mb-6 last:mb-4">
                        <label for="email" class="block text-gray-900 text-sm dark:text-gray-200 font-medium mb-2">
                            {% trans 'Email' %}
                            <span class="text-red-600">*</span>
                        </label>
                        <input type="email" name="email" autocomplete="email"
                            class="border bg-white font-medium min-w-20 rounded-md shadow-sm text-gray-500 text-sm focus:ring focus:ring-primary-300 focus:border-primary-600 focus:outline-none group-[.errors]:border-red-600 group-[.errors]:focus:ring-red-200 dark:bg-gray-900 dark:border-gray-700 dark:text-gray-400 dark:focus:border-primary-600 dark:focus:ring-primary-700 dark:focus:ring-opacity-50 dark:group-[.errors]:border-red-500 dark:group-[.errors]:focus:ring-red-600/40 px-3 py-2 w-full"
                            required="" id="email">
                        <span class="error" id="emailError" style="display:none;color:red;"></span>
                    </div>

                    <div class="submit-row">
                        <button type="submit"
                            class="bg-primary-600 border border-transparent flex flex-row font-semibold group items-center justify-center py-2 rounded-md text-sm text-white w-full hover:bg-primary-700 transition-colors duration-300" >
                            {% trans 'Reset Password' %}
                            <i class="material-symbols-outlined ml-2 relative right-0 text-lg transition-all group-hover:-right-1">arrow_forward</i>
                        </button>
                    </div>
                </form>

                <div class="border-top pt-3">
                    <small class="text-muted">
                        {% trans 'Remember your password?' %}
                        <a class="ml-2" href="{% url 'login' %}">
                            {% trans 'Log In' %}
                        </a>
                    </small>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block extrastyle %}
    {{ block.super }}
    <style>
        /* Additional styles can be added here */
        /* Example: Custom hover effect for the login button */
        .bg-primary-600:hover {
            background-color: #072d4e; /* Darker shade of primary color on hover */
        }
        /* Custom style for the "Log in" text */
        .bg-primary-600 span {
            color: black; /* Set text color to black */
        }
        /* Ensure button color stays consistent */
        .bg-primary-600 {
            background-color: #072d4e; /* Set primary button background color */
            color: white; /* Set primary button text color */
        }
        .text-primary-600 {
            --tw-text-opacity: 1;
            color: #072d4e;
        }
    </style>
{% endblock %}

{% block extrascript %}
    {{ block.super }}
    <script>
        function validatePasswordResetForm() {
            var valid = true;

            // Clear previous errors
            document.getElementById('emailError').style.display = 'none';

            // Get form values
            var email = document.getElementById('email').value;

            // Validate email
            var emailPattern = /^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,6}$/;
            if (!emailPattern.test(email)) {
                document.getElementById('emailError').innerText = "Please enter a valid email address.";
                document.getElementById('emailError').style.display = 'block';
                valid = false;
            }

            return valid;
        }
    </script>
{% endblock %}

users/templates/users/password_reset_complete.html
{% extends "django_classified/_base.html" %}
{% block body %}
    <div class="alert alert-info">
        Your password has been set.
    </div>
    <a href="{% url 'login' %}">Sign In Here</a>
{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends "django_classified/_base.html" %}
{% load crispy_forms_tags %}
{% block body %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Reset Password</button>
            </div>
        </form>
    </div>
{% endblock %}

users/templates/users/password_reset_done.html
{% extends "django_classified/_base.html" %}
{% block body %}
    <div class="alert alert-info">
        An email has been sent with instructions to reset your password
    </div>
{% endblock %}